### ISSUE TITLE
Have reasonable process for notifying PhET devs when contributor has signed CLA

### ISSUE THREAD

**Issue by liammulh** [phetsims/community#10]
Ideally we could automate notifying PhET devs if a contributor signed the CLA, and then their pull request can progress. See https://github.com/phetsims/community/issues/6#issuecomment-1460360817 for more info.

**Comment by liammulh** [comment]
In the linked comment, @samreid shared this link: https://github.com/cla-assistant/cla-assistant.

**Comment by BLFiedler** [comment]
This issue does seem like a problem only if we suddenly become flooded with contributors, but one medium tier option (not automated):

I have some local edits to the PULL_REQUEST_TEMPLATE that might work here as a stopgap. We could just encourage contributors to follow up their pull request with a comment in the pull request confirming that they signed the CLA (and perhaps some kind of evidence). If no comment, then we don't address the pull request?

Here's a version that could be added:
 
> ## BEFORE YOU SUBMIT - ACTION REQUIRED
> 
> By submitting this PR, I am indicating to the phetsims maintainers that I have read and understood the [contributing guidelines](../CONTRIBUTING.md) and that this PR follows those guidelines to the best of my knowledge. 
> 
> I also understand that my PR cannot be merged until I have signed the [Contributor License Agreement](../CLA.md). **Please indicate in a separate comment below this that you have successfully signed the CLA**

**Comment by brettfiedler** [comment]
Transfer to https://github.com/scenerystack/community/issues/6
