### ISSUE TITLE
How will we handle merge conflicts?

### ISSUE THREAD

**Issue by liammulh** [phetsims/community#11]
If a PR gets stale, there could potentially be a lot of merge conflicts. We can use this issue for discussion. We might also want to think about how we'd like to handle Git history when we merge. Do we aim for accuracy (preserve all commits in the PR) or do we aim for readability (squash all commits into one, then merge)?

**Comment by BLFiedler** [comment]
Logging @liammulh's poll here in Slack:

> Simple Poll
> APP  [15 minutes ago](https://phetsims.slack.com/archives/C6HPE0J91/p1678471953222639)
> When it comes to Git history in pull requests (PRs), do we aim for accuracy (preserve all commits in the PR) or do we aim for readability (squash all commits into one, then merge)?
> :one: accuracy    2
> [@mjkauzmann](https://phetsims.slack.com/team/U6DFWDG1Z)
> , 
> [@samreid](https://phetsims.slack.com/team/U6DKKJ2FN)
> :two: readability
> Created by 
> [@Liam](https://phetsims.slack.com/team/U79UUKBA5)
>  with /poll

> 
> Liam Mulhall
> The disadvantage to 1 is that if a PR needs to be rebased, the Git history could end up looking very ugly.
> The disadvantage to 2 is that the Git history doesn’t accurately reflect all of the commits/decisions that went into the PR.
> 
> Michael Kauzmann
> I feel like you said that 1 is more ugly, but to me it would be less ugly. A giant changeset for one commit is much harder to go back to while trying to debug a line of code. The main concern with (1) for me is that we would have to defer to the PR authors judgement about what a good commit is.
> 
> Sam Reid
> I’d be inclined to start with (1) accuracy, but then abandon it in the future if the rebasing overhead is too much.
> 
> Chris Malley
> What is the context for this poll?
> 
> Liam Mulhall
> As part of the POSE grant we are trying to be more open to outside contributions.
> 
> Chris Malley
> Who is making the pull requests? Who is reviewing the pull requests? Etc.
> 
> Liam Mulhall
> Who is making the pull requests?
> Anyone who wants to contribute.
> Who is reviewing the pull requests?
> Presumably the responsible dev for the repo where the PR was created.
> 
> Chris Malley
> I see. So PhET is looking to establish a process for pull requests. Is minimizing time to review the requests desirable?
> 
> Liam Mulhall
> Is minimizing time to review the requests desirable?
> Since we develop on master and not on feature branches, it’s possible a PR could get stale quickly, so a quick turnaround for a PR would be ideal. However, it probably wouldn’t be a good idea to rush them.
> 
> Chris Malley
> My first recommendation is to encourage small pull requests, and strongly discourage combining multiple issues into the same pull request. Because https://www.swarmia.com/blog/why-small-pull-requests-are-better
> swarmia.comswarmia.com
> [Why small pull requests are better](https://www.swarmia.com/blog/why-small-pull-requests-are-better)
> Eight great reasons why you should write small pull requests and tips on how to do it in practice. (2 MB)
> 
> Chris Malley
> If pull requests are indeed small, I don’t feel the need to choose one of the poll options as “The Way” for all pull requests. And it’s impossible for me to make a choice before we’ve seen some pull requests. The nature of the pull requests we receive will inform how we handle them, and how our processing of them evolves.  If I must choose one (as a place to start), I’ll choose “accuracy”, since it gives me the most information.  (edited)

**Comment by liammulh** [comment]
I think for now, we will try to keep it simple and just ask people to rebase from master, and we will preserve the Git history from their PR.

If we find the Git history too noisy, we can change this process.
