### ISSUE TITLE
How do we handle cross-repo PRs?

### ISSUE THREAD

**Issue by liammulh** [phetsims/community#12]
If a PR touches files in multiple repos, how do we handle that? Presumably other projects have had this problem.

**Comment by liammulh** [comment]
I did some googling, and I don't think there's an out-of-the-box solution for this on GitHub (yet). It looks like there are other people who want this. See https://github.com/community/community/discussions/13733.

One solution would be to ask contributors to open one PR per repo. That might be hard to manage.

Another solution would be to have them open a single PR in one repo and then in a comment in that PR paste their `git diff` for the other repos. That might be easier to track, but it wouldn't allow us to leverage GitHub's user interface for the diffs.

**Comment by brettfiedler** [comment]
Transferred to https://github.com/scenerystack/community/issues/5
