### ISSUE TITLE
Core set of common code repos should link to the `CONTRIBUTING.md` file in this repo

### ISSUE THREAD

**Issue by liammulh** [phetsims/community#13]
All public PhET repos should link to the `CONTRIBUTING.md` file in this repo. I think we'd need to write a script that updates existing ones, or perhaps there's a way to regenerate them based on a template. Sim devs will know more about this than me.

**Comment by BLFiedler** [comment]
For now, the CONTRIBUTING.md will focus on the core set of common code repos listed in https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#source-code-and-dependencies.

We are intentionally excluding sim repos for OSE efforts.

**Comment by liammulh** [comment]
In https://github.com/phetsims/community/commit/4f94423df7880b343e9d73c6cf7901df2c36bb08, I added a script that appends a note about the contributing doc and a link to it to each of the repos in https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#source-code-and-dependencies.

**Comment by samreid** [comment]
@liammulh and I addressed this one, closing.
