### ISSUE TITLE
community repo is missing the standard GitHub label set

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/community#20]
Assigning to @samreid who created this repo.  Did you follow the [New Repository Checklist](https://github.com/phetsims/phet-info/blob/master/checklists/new-repo-checklist.md)? 

> - [ ] Apply GitHub labels. See [github-labels/README.md](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md).

**Comment by samreid** [comment]
The decision to use a different label set for this repo was documented in https://github.com/phetsims/community/issues/4, closing.
