### ISSUE TITLE
Linting is messed up for community repo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/community#21]
https://github.com/phetsims/community/issues/19 was cause by the fact that `grunt lint-everything` visits the community repo. But it's currently impossible to `cd community; grunt lint`.  So how exactly is one supposed to run lint for their work in community, or have git-hooks check their work?

**Comment by samreid** [comment]
Our normal Gruntfile.js pattern will not work with the package.json as it is.  Because the package.json says "type": "module", and if you cd community; grunt lint then it errors with:

```
~/apache-document-root/main/community$ grunt lint
Loading "Gruntfile.js" tasks...ERROR
>> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/samreid/apache-document-root/main/community/Gruntfile.js from /Users/samreid/apache-document-root/main/community/node_modules/grunt/lib/grunt/task.js not supported.
>> Gruntfile.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
>> Instead rename Gruntfile.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/samreid/apache-document-root/main/community/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
Warning: Task "lint" not found. Use --force to continue.
```

**Comment by kathy-phet** [comment]
In discussion with @samreid and @BLFiedler, we discussed that it would be OK to keep this work around of not linting community repo, until the scripts outlived their usefulness. So @liammulh, these scripts can stay in community as we work on refining our processes here. 

Also, this may become lintable in the future, if we do the move to deno and move away from grunt, etc.

**Comment by samreid** [comment]
@liammulh and I decided to migrate the scripts to perennial for now.  @liammulh will take the lead.  The lint.js workaround will also be removed chipper/js/grunt/lint.js

**Comment by liammulh** [comment]
Okay, scripts migrated to perennial, and the workaround has been removed.
