### ISSUE TITLE
PhET APIs are constantly evolving and improving.

### ISSUE THREAD

**Issue by zzz-creator** [phetsims/community#24]
PhET APIs are constantly evolving and improving. 

In our current structure, that sometimes means making changes that are not backward compatible. We know that third-party developers are using our libraries, and breaking changes are a drag - especially if you don’t know about them!

Watch this thread where we will post notifications of breaking changes to our APIs. You can subscribe to this thread in the sidebar under the Notifications header.

_Originally posted by @BLFiedler in https://github.com/phetsims/community/discussions/22_

**Comment by zzz-creator** [comment]
I am receiving a error:
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 327946257

Varnish cache server

**Comment by BLFiedler** [comment]
Hi @zzz-creator,

Thanks for reaching out and posting this issue!

Could you provide more detail regarding the error? What were you doing when you received the error? What steps led to seeing this error, and where did the error appear?

The comment you quote in your original post references the use of the PhET source code API for creating web interactives, which is the intent of this repository. If you're having trouble using the API, I encourage you to make a posting in our forum dedicated to that purpose: https://github.com/orgs/phetsims/discussions

If this is an issue regarding using a specific simulation or navigating the PhET website (phet.colorado.edu), I encourage you to contact us at phethelp@colorado.edu.
