### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/community#3]
The README is the main landing page for anyone visiting the repository.

It needs to contain the purpose of the repo, the audience, requirements, build process, roadmap, etc.

e.g.,

> What does this project do?
> Why is this project useful?
> How do I get started?
> Where can I get more help, if I need it?

### Resources:
- https://github.com/matiassingers/awesome-readme
- https://opensource.guide/starting-a-project/#writing-a-readme

**Comment by jonathanolson** [comment]
> Each library is housed PhET uses many or all of these libraries when creating an educational interactive simulation

What is this sentence trying to say? I couldn't parse it.

**Comment by brettfiedler** [comment]
Looks like an idea fragment that got interrupted. I'd disregard everything before "PhET" in that sentence.

**Comment by brettfiedler** [comment]
Completed in its first iteration.
