### ISSUE TITLE
Flesh out `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by marlitas** [phetsims/community#6]
As part of our POSE work we are creating a draft for Contributing.md including a pull request process. This issue will track that work.

Here are previous Doughnominators updates prior to the creation of this issue:
Pilot and document a path to Pull Request for an outside contributor (for e.g., Scenery) including Contributor License Agreement (subset of next task)

2/24: Holding off on this for now
2/27: Can we actually try this as an outside contributor? Maybe on an issue that we already have on our list?
- MK: maybe we're over thinking. Let's just try something and go from there. It doesn't have to be the perfect idea.
- AV: let's schedule a subgroup meeting for this ( LM, MS, AV, MK)
- JO: I'm curious and I think this would be an interesting convo.
- MS: Let's maybe hold off on this till tomorrow (Tuesday)

2/28: No progress as of yet.

3/1: No progress yet
- LM: still handling Rosetta and balancing QA.
- MS: I'll look through candidate PR issues in Scenery.

3/3: No progress. Tentative meeting set for 12 MST on Monday.

3/6: Meeting tomorrow! 

3/7: Meeting today at noon!
MS: threw some issues to consider for PR in slack channel.

**Comment by BLFiedler** [comment]
Moved this issue to the community repo, where this document will ultimately be housed.

**Comment by marlitas** [comment]
@BLFiedler Do we also want to move the document over to that repo? Or wait until it's ready?

**Comment by marlitas** [comment]
Let's move TODO's to their own issues. @marlitas volunteered to do that.

**Comment by BLFiedler** [comment]
> @BLFiedler Do we also want to move the document over to that repo? Or wait until it's ready? https://github.com/phetsims/phet-info/blob/master/contributors/CONTRIBUTING.md

Feel free to bring it over here. We may end up pointing toward certain helpful documentation in phet-info from here, but files intended only for external contributors should live here.

Also, posting a resource we've been using for organizing the OSE setup:
- https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by zepumph** [comment]
As of https://github.com/phetsims/community/commit/8682d9e5ab1ccce9a8247b8bc93717672af104e3 we now have two copies of CONTRIBUTING. One in community and one in phet-info. 

I promoted the TODOs in the phet-info copy to this issue:


Still TODO:

- [ ] Sort out where the copy of CONTRIBUTING should be. community/ or phet-info/
- [ ] We should make a pull request template.
- [ ] How do we know when people have signed the CLA?
- [ ] If things sit for a while, how to best handle merge conflicts.
- [ ] How to handle cross repo pull requests?
- [ ] Link this from all repo READMEs?

**Comment by liammulh** [comment]
> As of https://github.com/phetsims/community/commit/8682d9e5ab1ccce9a8247b8bc93717672af104e3 we now have two copies of CONTRIBUTING. One in community and one in phet-info.

I thought @BLFiedler wanted the contrib doc in this repo.

> Still TODO:

All of those TODOs are now issues in this repo.

**Comment by zepumph** [comment]
Gotcha. Sounds nice! Should we delete the phet-info copy then?

**Comment by marlitas** [comment]
Here are the TODO issues:
- https://github.com/phetsims/community/issues/13
- https://github.com/phetsims/community/issues/12
- https://github.com/phetsims/community/issues/11
- https://github.com/phetsims/community/issues/10
- https://github.com/phetsims/community/issues/9

**Comment by liammulh** [comment]
> Gotcha. Sounds nice! Should we delete the phet-info copy then?

Removed in https://github.com/phetsims/phet-info/commit/28a7b7c6ec61861f8292ece72d3d795136626b69.

**Comment by brettfiedler** [comment]
Transferred to https://github.com/scenerystack/community/issues/7
